In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
# Python의 리스트로부터 Numpy 배열을 만든다.
print(a)

[0 1 2 3 4 5]


In [5]:
import numpy as np

b = np.array([[0, 1, 2], [3, 4, 5]])
# 2중 리스트로부터 Numpy 2차원 배열을 만든다.
print(b)

[[0 1 2]
 [3 4 5]]


In [7]:
import numpy as np

c = np.array([[[0, 1, 2], [3, 4, 5]],[[5, 4, 3], [2, 1, 0]]])
# 3중 리스트로부터 Numpy 3차원 배열을 만든다.
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [11]:
import numpy as np

d = np.zeros(8) # 0이 8개 저장된 배열
print(d)

e = np.ones(8) # 1이 8개 저장된 배열
print(e)

f = np.arange(8) # 0부터 7까지 저장된 배열
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [13]:
import numpy as np

a = np.array([[0, 1, 2], 
              [3, 4, 5]]) # 2x3의 2차원 배열

print(np.shape(a)) # a의 형태를 출력(행의 수, 열의 수)


(2, 3)


In [14]:
print(len(a)) # a의 행의 수를 얻는다.

2


In [15]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2차원 배열

print(a)
print()
print(a + 3) # 각 요소에 3을 더한다.
print()
print(a * 3) # 각 요소에 3을 곱한다.    

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [16]:
b = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2차원 배열

c = np.array([[2, 0, 1],
             [5, 3, 4]]) # 2차원 배열

print(b)
print()
print(c)
print()
print(b + c) 
print()
print(b * c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [17]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[3]) # 인덱스를 지정

4


In [18]:
a[2] = 9
print(a)


[1 2 9 4 5]


In [20]:
b = np.array([[0, 1, 2],
             [3, 4, 5]])

print(b[1, 2]) # b[1][2]와 같다.

5


In [21]:
b[1, 2] = 9

print(b)

[[0 1 2]
 [3 4 9]]


In [23]:
c = np.array([[0, 1, 2],
              [3, 4, 5]])

print(c[1, :]) # 인덱스가 1인 행을 취득

print()

c[:, 1] = np.array([6, 7]) # 인덱스가 1인 열을 교체
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [24]:
import numpy as np

def my_func(x):
    y = x * 2 + 1
    return y

a = np.array([[0, 1, 2],
              [3, 4, 5]]) #2차원 배열
b = my_func(a) # 인수로서 배열을 전달, 반환값으로서 배열을 받는다.

print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [25]:
import numpy as np 

a = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2차원 배열

print("합계:", np.sum(a))
print("평균값:", np.average(a))
print("최댓값:", np.max(a))
print("최솟값:", np.min(a))

합계: 15
평균값: 2.5
최댓값: 5
최솟값: 0


In [26]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]]) # 2차원 배열
b = np.array([[5, 4, 3],
              [2, 1, 0]]) # 2차원 배열

print(a + b) # 합
print()
print(a - b) # 차
print()
print(a * b) # 곱

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
